version: "2.0"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./app/data/migrations:/db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atividade
      MYSQL_USER: manuel
      MYSQL_PASSWORD: 123
